### ISSUE TITLE
Alinhamento do botão "encontrar"

### ISSUE THREAD

**Issue by oliveiralex** [geovanigeraldi/github-user-search#1]
Olá Geovani,

Seu trabalho foi aceito, parabéns! Para ficar 100%, sugiro que o alinhamento do botão "encontrar seja feito. Além disso, algo que facilita muito é que quando você passar o mouse no botão ele fique com a opção indicando que é possível clicar naquele link. Neste caso, basta incluir no css o comando 

> cursor: pointer;

Abraço e bons estudos

**Comment by geovanigeraldi** [comment]
Alteração realizada =)

**Comment by oliveiralex** [comment]
Obrigado Geovani!!
Abraço
